//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kullanici
    {
        public int Id { get; set; }
        [DataType(DataType.Password)]
        public string sifre { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string kullanici_adi { get; set; }
        public virtual resimler resimler { get; set; }
    }
}
