//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Kullanici
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "It is required to fill this area.", AllowEmptyStrings = false)]
        [DisplayName("Username :")]
        public string kullanici_adi { get; set; }
        [Required(ErrorMessage = "It is required to fill this area.", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [DisplayName("Password :")]
        public string sifre { get; set; }

        [DisplayName("Name :")]
        public string ad { get; set; }

        [DisplayName("Surname :")]
        public string soyad { get; set; }

        [DisplayName("Tel :")]
        public string tel { get; set; }

        [DisplayName("E-mail :")]
        public string email { get; set; }
    
        public virtual resimler resimler { get; set; }
    }
}
